version: '3'

services:
    app:
      image: httpd:latest

    proxy:
      image: xtrasimplicity/nginx_proxy:dev
      build: .
      depends_on:
        - app
      env_file:
        - config.env
      volumes:
        - ./data/ssl:/etc/ssl/private/
      ports:
        - 8080:80
        - 4434:443

